# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 03:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(max_length=254)),
                ('action', models.CharField(max_length=254)),
                ('itemname', models.CharField(max_length=254)),
                ('chartingla', models.CharField(max_length=254)),
                ('latitude', models.CharField(max_length=254)),
                ('longitude', models.CharField(max_length=254)),
                ('latdd', models.CharField(max_length=254)),
                ('longdd', models.CharField(max_length=254)),
                ('publishedd', models.CharField(max_length=254)),
                ('kapp', models.CharField(max_length=254)),
                ('rncpanel', models.CharField(max_length=254)),
                ('rncposted', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'NTMS',
            },
        ),
    ]
