# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ntm',
            name='action',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='chart',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='chartingla',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='itemname',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='kapp',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='latdd',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='latitude',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='longdd',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='longitude',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='publishedd',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='rncpanel',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ntm',
            name='rncposted',
            field=models.CharField(max_length=1000),
        ),
    ]
