# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='salary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
